services:
  db:
    image: postgres:${COMPOSE_POSTGRES_IMAGE_TAG:-17}
    command:
      [
        'postgres',
        '-p',
        '${COMPOSE_POSTGRES_PORT:-5432}',
        '-c',
        'log_statement=all',
        '-c',
        'log_destination=stderr',
      ]
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${COMPOSE_POSTGRES_USER:-incident_bot} -d ${COMPOSE_POSTGRES_DB:-incident_bot} -p ${COMPOSE_POSTGRES_PORT:-5432}',
        ]
      interval: 15s
      timeout: 10s
      retries: 10
    hostname: db
    environment:
      POSTGRES_DB: ${COMPOSE_POSTGRES_DB:-incident_bot}
      POSTGRES_PASSWORD: ${COMPOSE_POSTGRES_PASSWORD:-somepassword}
      POSTGRES_USER: ${COMPOSE_POSTGRES_USER:-incident_bot}
    ports:
      - ${COMPOSE_POSTGRES_PORT:-5432}:${COMPOSE_POSTGRES_PORT:-5432}
    networks:
      - inc_bot_network
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SLACK_APP_TOKEN: ''
      SLACK_BOT_TOKEN: ''
      SLACK_USER_TOKEN: ''
      POSTGRES_HOST: ${COMPOSE_POSTGRES_HOST:-db}
      POSTGRES_DB: ${COMPOSE_POSTGRES_DB:-incident_bot}
      POSTGRES_USER: ${COMPOSE_POSTGRES_USER:-incident_bot}
      POSTGRES_PASSWORD: ${COMPOSE_POSTGRES_PASSWORD:-somepassword}
      POSTGRES_PORT: ${COMPOSE_POSTGRES_PORT:-5432}
      ENABLE_API_DOCS: 'true'
      # PAGERDUTY_API_TOKEN: ''
      # PAGERDUTY_API_USERNAME: ''
      # STATUSPAGE_API_KEY: ''
      # STATUSPAGE_PAGE_ID: ''
      # ATLASSIAN_API_URL: ''
      # ATLASSIAN_API_USERNAME: ''
      # ATLASSIAN_API_TOKEN: ''
      # ZOOM_ACCOUNT_ID: ''
      # ZOOM_CLIENT_ID: ''
      # ZOOM_CLIENT_SECRET: ''
    ports:
      - target: 3000
        published: ${COMPOSE_API_PORT:-3000}
        protocol: tcp
        mode: host
    volumes:
      # Wherever the config file lives, root by default
      - ./config.yaml:/app/config.yaml
    networks:
      - inc_bot_network
networks:
  inc_bot_network:
    driver: bridge
