{{- if .Values.externalSecret.enabled }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.secretName }}
spec:
  backendType: {{ .Values.externalSecret.backendType }}
  projectId: {{ .Values.externalSecret.projectId }}
  dataFrom:
    {{- range .Values.externalSecret.dataFrom }}
    - {{ . }}
    {{- end }}
{{- end }}
