"""Add columns to PagerDutyIncidentRecord

Revision ID: 70dc94de8fe2
Revises: c1d6d526637a
Create Date: 2024-09-26 12:28:45.445767

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "70dc94de8fe2"
down_revision = "c1d6d526637a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pagerdutyincidentrecord",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "pagerdutyincidentrecord",
        sa.Column("updated_at", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "pagerdutyincidentrecord",
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pagerdutyincidentrecord", "created_at")
    op.drop_column("pagerdutyincidentrecord", "updated_at")
    op.drop_column("pagerdutyincidentrecord", "url")
    # ### end Alembic commands ###
