"""Add columns to IncidentRecord

Revision ID: c084a30ce811
Revises: 70dc94de8fe2
Create Date: 2024-10-03 22:01:59.104401

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c084a30ce811"
down_revision = "70dc94de8fe2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "incidentrecord",
        sa.Column("has_private_channel", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incidentrecord", "has_private_channel")
    # ### end Alembic commands ###
