"""Initial commit

Revision ID: d3da32cf941c
Revises: a356e9f16eef
Create Date: 2025-09-02 22:17:18.596856

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d3da32cf941c"
down_revision = "a356e9f16eef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("opsgenieincidentrecord")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opsgenieincidentrecord",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("parent", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["parent"],
            ["incidentrecord.id"],
            name=op.f("opsgenieincidentrecord_parent_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("opsgenieincidentrecord_pkey")
        ),
    )
    # ### end Alembic commands ###
