"""Initial commit

Revision ID: eeebefcd37d6
Revises: 3f8c2a1b9d04
Create Date: 2026-05-30 17:31:18.739235

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "eeebefcd37d6"
down_revision = "3f8c2a1b9d04"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("maintenancewindowrecord")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_constraint(
        op.f("gitlabissuerecord_parent_fkey"),
        "gitlabissuerecord",
        type_="foreignkey",
    )
    op.create_index(
        op.f("ix_incidentevent_parent"),
        "incidentevent",
        ["parent"],
        unique=False,
    )
    op.drop_constraint(
        op.f("incidentparticipant_parent_fkey"),
        "incidentparticipant",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("jiraissuerecord_parent_fkey"),
        "jiraissuerecord",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("pagerdutyincidentrecord_parent_fkey"),
        "pagerdutyincidentrecord",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("phareincidentrecord_parent_fkey"),
        "phareincidentrecord",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("postmortemrecord_parent_fkey"),
        "postmortemrecord",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("statuspageincidentrecord_parent_fkey"),
        "statuspageincidentrecord",
        type_="foreignkey",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("statuspageincidentrecord_parent_fkey"),
        "statuspageincidentrecord",
        "incidentrecord",
        ["parent"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("postmortemrecord_parent_fkey"),
        "postmortemrecord",
        "incidentrecord",
        ["parent"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("phareincidentrecord_parent_fkey"),
        "phareincidentrecord",
        "incidentrecord",
        ["parent"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("pagerdutyincidentrecord_parent_fkey"),
        "pagerdutyincidentrecord",
        "incidentrecord",
        ["parent"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("jiraissuerecord_parent_fkey"),
        "jiraissuerecord",
        "incidentrecord",
        ["parent"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("incidentparticipant_parent_fkey"),
        "incidentparticipant",
        "incidentrecord",
        ["parent"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_incidentevent_parent"), table_name="incidentevent")
    op.create_foreign_key(
        op.f("gitlabissuerecord_parent_fkey"),
        "gitlabissuerecord",
        "incidentrecord",
        ["parent"],
        ["id"],
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "maintenancewindowrecord",
        sa.Column(
            "channels",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "components",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("contact", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "description", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "end_timestamp",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "start_timestamp",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("maintenancewindowrecord_pkey")
        ),
    )
    # ### end Alembic commands ###
