import jwt

from fastapi import APIRouter, Header, HTTPException, Request, status
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates
from incidentbot.incident.core import Incident, IncidentRequestParameters
from incidentbot.models.response import SuccessResponse
from incidentbot.util.widget_token import verify_widget_token
from pathlib import Path
from pydantic import BaseModel

router = APIRouter()
templates = Jinja2Templates(
    directory=str(Path(__file__).parent.parent.parent / "templates")
)


class WidgetIncidentRequest(BaseModel):
    incident_description: str
    severity: str
    incident_components: str
    incident_impact: str | None = None
    is_security_incident: bool = False
    user: str | None = None


def _check_token(token: str | None) -> dict:
    if not token:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Missing widget token",
        )
    try:
        return verify_widget_token(token)
    except jwt.InvalidTokenError as exc:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=f"Invalid widget token: {exc}",
        )


@router.get("/widget/incident", response_class=HTMLResponse)
async def incident_widget(request: Request, token: str | None = None):
    """
    Serve the incident creation widget. Requires a valid signed widget token
    generated by the Matrix bot when registering the widget in a room.
    """
    payload = _check_token(token)
    return templates.TemplateResponse(
        "incident_widget.html",
        {
            "request": request,
            "token": token,
            "room_id": payload.get("room_id", ""),
        },
    )


@router.post("/widget/api/incident", status_code=status.HTTP_201_CREATED)
async def widget_create_incident(
    body: WidgetIncidentRequest,
    x_widget_token: str | None = Header(default=None),
) -> SuccessResponse:
    """
    Create an incident from the widget. Authenticated by the widget token
    (X-Widget-Token header) rather than the regular user JWT.
    """
    _check_token(x_widget_token)

    try:
        incident = Incident(
            params=IncidentRequestParameters(
                incident_description=body.incident_description,
                severity=body.severity,
                incident_components=body.incident_components,
                incident_impact=body.incident_impact,
                is_security_incident=body.is_security_incident,
                created_from_web=True,
                user=body.user,
            )
        )
        incident.start()
        return SuccessResponse(result="success", message="Incident created")
    except Exception as error:
        raise HTTPException(status_code=500, detail=str(error))
