import jwt

from fastapi import APIRouter, Header, HTTPException, Request, status
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates
from incidentbot.configuration.settings import settings
from incidentbot.incident.core import Incident, IncidentRequestParameters
from incidentbot.incident.event import EventLogHandler
from incidentbot.models.database import IncidentParticipant, IncidentRecord, engine
from incidentbot.models.response import SuccessResponse
from incidentbot.platform import get_adapter
from incidentbot.util.widget_token import verify_widget_token
from pathlib import Path
from pydantic import BaseModel
from sqlmodel import Session, select
from typing import Literal

router = APIRouter()
templates = Jinja2Templates(
    directory=str(Path(__file__).parent.parent.parent / "templates")
)


class WidgetIncidentRequest(BaseModel):
    incident_description: str
    severity: str
    incident_components: str
    incident_impact: str | None = None
    is_security_incident: bool = False
    user: str | None = None


class WidgetIncidentRoomUpdateRequest(BaseModel):
    action: Literal["join_role", "set_severity", "set_status", "resolve"]
    role: str | None = None
    severity: str | None = None
    status: str | None = None
    user: str | None = None


def _check_token(token: str | None) -> dict:
    if not token:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Missing widget token",
        )
    try:
        return verify_widget_token(token)
    except jwt.InvalidTokenError as exc:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=f"Invalid widget token: {exc}",
        )


def _get_incident_for_room(room_id: str) -> IncidentRecord:
    with Session(engine) as session:
        incident = session.exec(
            select(IncidentRecord).where(IncidentRecord.channel_id == room_id)
        ).first()

    if not incident:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"No incident found for room {room_id}",
        )

    return incident


def _update_room_topic(adapter, incident: IncidentRecord) -> None:
    with Session(engine) as session:
        lead_participant = session.exec(
            select(IncidentParticipant).where(
                IncidentParticipant.parent == incident.id,
                IncidentParticipant.is_lead == True,
            )
        ).first()

    topic = (
        f"Severity: {incident.severity.upper()} | "
        f"Status: {incident.status.title()}"
    )
    if lead_participant:
        topic += (
            f" | {lead_participant.role.replace('_', ' ').title()}: "
            f"{lead_participant.user_name}"
        )

    adapter.set_room_topic(room_id=incident.channel_id, topic=topic)


@router.get("/widget/incident", response_class=HTMLResponse)
async def incident_widget(request: Request, token: str | None = None):
    """
    Serve the incident creation widget. Requires a valid signed widget token
    generated by the Matrix bot when registering the widget in a room.
    """
    payload = _check_token(token)
    return templates.TemplateResponse(
        "incident_widget.html",
        {
            "request": request,
            "token": token,
            "room_id": payload.get("room_id", ""),
        },
    )


@router.get("/widget/incident-room", response_class=HTMLResponse)
async def incident_room_widget(request: Request, token: str | None = None):
    payload = _check_token(token)
    room_id = payload.get("room_id", "")
    incident = _get_incident_for_room(room_id)
    return templates.TemplateResponse(
        "incident_room_widget.html",
        {
            "request": request,
            "token": token,
            "room_id": room_id,
            "incident": incident,
            "roles": incident.roles_all or [],
            "severities": incident.severities or [],
            "statuses": incident.statuses or [],
        },
    )


@router.post("/widget/api/incident", status_code=status.HTTP_201_CREATED)
async def widget_create_incident(
    body: WidgetIncidentRequest,
    x_widget_token: str | None = Header(default=None),
) -> SuccessResponse:
    """
    Create an incident from the widget. Authenticated by the widget token
    (X-Widget-Token header) rather than the regular user JWT.
    """
    _check_token(x_widget_token)

    try:
        incident = Incident(
            params=IncidentRequestParameters(
                incident_description=body.incident_description,
                severity=body.severity,
                incident_components=body.incident_components,
                incident_impact=body.incident_impact,
                is_security_incident=body.is_security_incident,
                created_from_web=True,
                user=body.user,
            )
        )
        incident.start()
        return SuccessResponse(result="success", message="Incident created")
    except Exception as error:
        raise HTTPException(status_code=500, detail=str(error))


@router.post("/widget/api/incident-room", status_code=status.HTTP_200_OK)
async def widget_update_incident_room(
    body: WidgetIncidentRoomUpdateRequest,
    x_widget_token: str | None = Header(default=None),
) -> SuccessResponse:
    payload = _check_token(x_widget_token)
    room_id = payload.get("room_id", "")
    adapter = get_adapter()

    with Session(engine) as session:
        incident = session.exec(
            select(IncidentRecord).where(IncidentRecord.channel_id == room_id)
        ).first()
        if not incident:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"No incident found for room {room_id}",
            )

        match body.action:
            case "join_role":
                if not body.user or not body.role:
                    raise HTTPException(
                        status_code=status.HTTP_400_BAD_REQUEST,
                        detail="Joining a role requires both user and role",
                    )
                if body.role not in (incident.roles_all or []):
                    raise HTTPException(
                        status_code=status.HTTP_400_BAD_REQUEST,
                        detail=f"Invalid role '{body.role}'",
                    )
                existing = session.exec(
                    select(IncidentParticipant).where(
                        IncidentParticipant.parent == incident.id,
                        IncidentParticipant.role == body.role,
                        IncidentParticipant.user_id == body.user,
                    )
                ).first()
                if existing:
                    return SuccessResponse(
                        result="success",
                        message=f"You have already joined as {body.role}",
                    )

                display_name = adapter.get_user_display_name(body.user)
                role_config = settings.roles.get(body.role)
                participant = IncidentParticipant(
                    is_lead=role_config.is_lead if role_config else False,
                    parent=incident.id,
                    role=body.role,
                    user_id=body.user,
                    user_name=display_name,
                )
                session.add(participant)
                session.commit()

                role_label = body.role.replace("_", " ").title()
                adapter.send_text(
                    room_id,
                    f"{display_name} joined the incident as {role_label}.",
                )
                EventLogHandler.create(
                    event=f"{display_name} joined the incident as {role_label}",
                    incident_id=incident.id,
                    incident_slug=incident.slug,
                    source="system",
                    user=body.user,
                )
                return SuccessResponse(
                    result="success",
                    message=f"Joined as {role_label}",
                )

            case "set_severity":
                if not body.severity:
                    raise HTTPException(
                        status_code=status.HTTP_400_BAD_REQUEST,
                        detail="Setting severity requires a severity value",
                    )
                if body.severity not in (incident.severities or []):
                    raise HTTPException(
                        status_code=status.HTTP_400_BAD_REQUEST,
                        detail=f"Invalid severity '{body.severity}'",
                    )
                incident.severity = body.severity
                session.add(incident)
                session.commit()

                _update_room_topic(adapter, incident)
                adapter.send_text(
                    room_id,
                    f"Incident severity updated to {body.severity.upper()}.",
                )
                EventLogHandler.create(
                    event=f"The incident severity was changed to {body.severity.upper()}",
                    incident_id=incident.id,
                    incident_slug=incident.slug,
                    source="system",
                    user=body.user,
                )
                return SuccessResponse(
                    result="success",
                    message=f"Severity updated to {body.severity.upper()}",
                )

            case "set_status" | "resolve":
                target_status = body.status
                if body.action == "resolve":
                    target_status = next(
                        (
                            name
                            for name, cfg in settings.statuses.items()
                            if cfg.final
                        ),
                        "resolved",
                    )
                if not target_status:
                    raise HTTPException(
                        status_code=status.HTTP_400_BAD_REQUEST,
                        detail="Setting status requires a status value",
                    )
                if target_status not in (incident.statuses or []):
                    raise HTTPException(
                        status_code=status.HTTP_400_BAD_REQUEST,
                        detail=f"Invalid status '{target_status}'",
                    )
                incident.status = target_status
                session.add(incident)
                session.commit()

                _update_room_topic(adapter, incident)
                adapter.send_text(
                    room_id,
                    f"Incident status updated to {target_status.title()}.",
                )
                EventLogHandler.create(
                    event=f"The incident status was changed to {target_status.title()}",
                    incident_id=incident.id,
                    incident_slug=incident.slug,
                    source="system",
                    user=body.user,
                )
                return SuccessResponse(
                    result="success",
                    message=f"Status updated to {target_status.title()}",
                )
